version: "3.1"

services:
  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./backend:/application


  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./backend:/application
      - ./frontend:/frontend
#      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "50000:80"


  postgres:
    build:
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  node:
    build:
#      context: ./frontend
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend:/frontend
    ports:
      - "50005:3000"
    command: npm start
#    command: sh -c "npx create-react-app . && npm start"
