version: "3.1"

services:
  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile
    volumes:
      - ./backend:/application
    depends_on:
      - postgres


  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./backend:/application
      - ./frontend:/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "50000:80"
    depends_on:
      - php-fpm


  postgres:
    build:
      dockerfile: ./docker/postgres/Dockerfile
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5431:5432'

  node:
    build:
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend/tochkarik:/frontend
    ports:
      - "5173:5173"
    command: npm run dev
