version: '1'

services:
  nginx:
    build: 
      context: .
      dockerfile: ./docker/volumes/build/nginx/Dockerfile
    volumes:
      - ./docker/volumes/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/usr/share/nginx/html
      - ./docker/volumes/logs/nginx:/var/log/nginx

    ports:
      - '80:80'
    depends_on:
      - php
  
  php:
    build: 
      context: .
      dockerfile: ./docker/volumes/build/php-fpm8.1/Dockerfile
    volumes:
      - ./app:/usr/share/nginx/html
      - ./app:/var/www/