version: "3.1"

services:
  php-fpm:
    build:
      dockerfile: docker/php-fpm/Dockerfile

  nginx:
    build:
      dockerfile: docker/nginx/Dockerfile


  postgres:
    build:
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}