security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            provider: app_user_provider
            json_login:
                username_path: username
                check_path: /api/login_check
                success_handler:
                    lexik_jwt_authentication.handler.authentication_success
                failure_handler:
                    lexik_jwt_authentication.handler.authentication_failure
            refresh_jwt:
                check_path: /api/token/api_refresh
        signup:
            pattern: ^/api/auth/signup
            stateless: true
            security: false
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            provider: app_user_provider

        refresh:
          pattern: ^/api/token/refresh
          stateless: true

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: appLoginPage
                check_path: appLoginPage

                enable_csrf: true
            logout:
                path: appLogout
                target: /

    access_control:
        - { path: ^/admin/auth/signin, roles: PUBLIC_ACCESS }
        - { path: ^/admin/auth/signup, roles: PUBLIC_ACCESS }
        - { path: ^/admin/auth/logout, roles: ROLE_ADMIN }
        - { path: ^/adminboard, roles: ROLE_ADMIN }

        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/login_check, roles: PUBLIC_ACCESS }
        - { path: ^/api/user, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/auth/signup, roles: PUBLIC_ACCESS }
        - { path: ^/api/token/api_refresh, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
