# frontend/Dockerfile

FROM node:16-alpine
# docker-compose run --rm node sh
#
WORKDIR /frontend

COPY ./frontend/package*.json ./
RUN #npm install
#
#COPY . .
#
EXPOSE 3000
#
#CMD [\"npm\", \"start\"]" > frontend/Dockerfile
