<?php

namespace App\Controller\Api\Private;

use App\Entity\PointTelemetry;
use Doctrine\DBAL\Exception\ConnectionException;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

#[Route('/api')]
class PointTelemetryController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    #[Route('/point_telemetry', name: 'apiGetAllTelemetry', methods: ['GET'])]
    public function getAllTelemetry(EntityManagerInterface $entityManager): JsonResponse
    {
        try {
            $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

            $telemetryRepository = $entityManager->getRepository(PointTelemetry::class);
            $telemetryRecords = $telemetryRepository->findAll();

            $telemetryData = [];
            foreach ($telemetryRecords as $telemetry) {
                $telemetryData[] = [
                    'id' => $telemetry->getId(),
                    'coordinates' => $telemetry->getCoordinates(),
                    'timeOfGenerate' => $telemetry->getTimeOfGenerate()->format('Y-m-d H:i:s'),
                    'description' => $telemetry->getDescription(),
                ];
            }
            return $this->json(['telemetry' => $telemetryData], JsonResponse::HTTP_OK);
        } catch (\Doctrine\DBAL\Exception\ConnectionException $e) {
            return $this->json(['error' => 'Database connection error: ' . $e->getMessage()], JsonResponse::HTTP_SERVICE_UNAVAILABLE);
        } catch (\Doctrine\DBAL\Exception $e) {
            return $this->json(['error' => 'Database error: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        } catch (\Exception $e) {
            return $this->json(['error' => 'Internal Server Error: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/point_telemetry/{id}', name: 'apiGetTelemetry', methods: ['GET'])]
    public function getTelemetryById(PointTelemetry $telemetry): JsonResponse
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        return $this->json([
            'id' => $telemetry->getId(),
            'coordinates' => $telemetry->getCoordinates(),
            'timeOfGenerate' => $telemetry->getTimeOfGenerate()->format('Y-m-d H:i:s'),
            'description' => $telemetry->getDescription(),
        ], JsonResponse::HTTP_OK);
    }

    #[Route('/point_telemetry/{id}', name: 'apiDeleteTelemetry', methods: ['DELETE'])]
    public function deleteTelemetry(
        PointTelemetry $telemetry,
        EntityManagerInterface $entityManager
    ): JsonResponse
    {
        try {
            $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

            $entityManager->remove($telemetry);
            $entityManager->flush();

            return $this->json(['status' => 'success'], JsonResponse::HTTP_NO_CONTENT);
        } catch (ConnectionException $e) {
            return $this->json(['error' => 'Database connection error: ' . $e->getMessage()], JsonResponse::HTTP_SERVICE_UNAVAILABLE);
        } catch (\Doctrine\DBAL\Exception $e) {
            return $this->json(['error' => 'Database error: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        } catch (\Exception $e) {
            return $this->json(['error' => 'Internal Server Error: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }

    #[Route('/point_telemetry_analytics', name: 'apiGetTelemetryAnalytics', methods: ['GET'])]
    public function getTelemetryAnalytics(EntityManagerInterface $entityManager): JsonResponse
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        try {
            $telemetryRepository = $entityManager->getRepository(PointTelemetry::class);

            // Points generated by rule
            $generatedPointsByRule = $telemetryRepository->findBy(['generatedByRule' => true]);
            $totalGeneratedPointsByRule = count($generatedPointsByRule);
            $visitedPointsByRule = array_filter($generatedPointsByRule, function($point) {
                return $point->isVisited();
            });
            $totalVisitedPointsByRule = count($visitedPointsByRule);

            // Points not generated by rule
            $generatedPointsNotByRule = $telemetryRepository->findBy(['generatedByRule' => false]);
            $totalGeneratedPointsNotByRule = count($generatedPointsNotByRule);
            $visitedPointsNotByRule = array_filter($generatedPointsNotByRule, function($point) {
                return $point->isVisited();
            });
            $totalVisitedPointsNotByRule = count($visitedPointsNotByRule);

            // Total points
            $totalGeneratedPoints = $totalGeneratedPointsByRule + $totalGeneratedPointsNotByRule;
            $totalVisitedPoints = $totalVisitedPointsByRule + $totalVisitedPointsNotByRule;

            $analytics = [
                'totalGeneratedPoints' => $totalGeneratedPoints,
                'generatedByRule' => $totalGeneratedPointsByRule,
                'generatedWithoutRule' => $totalGeneratedPointsNotByRule,
                'totalVisitedPoints' => $totalVisitedPoints,
                'visitedByRule' => $totalVisitedPointsByRule,
                'visitedWithoutRule' => $totalVisitedPointsNotByRule,
                'visitRateByRule' => $totalGeneratedPointsByRule > 0 ? ($totalVisitedPointsByRule / $totalGeneratedPointsByRule) * 100 : 0,
            ];


            return $this->json(['analytics' => $analytics], JsonResponse::HTTP_OK);
        } catch (\Exception $e) {
            return $this->json(['error' => 'Internal Server Error: ' . $e->getMessage()], JsonResponse::HTTP_INTERNAL_SERVER_ERROR);
        }
    }
}
